language: python
dist: xenial
python:
  - "nightly"
  - "3.10-dev"
  - "3.9"
  - "3.8"
  - "3.7"
script:
  - python -m unittest
  - python -m pylint pyfs
  - python -m pylint tests
jobs:
  allow_failures:
    - python: "nightly"
    - python: "3.10-dev"